substitutions:
  name: "sdl-lvgl"
  friendly_name: "SDL test system"
  # name: "sensecap-indicator"
  # friendly_name: "SenseCAP Indicator"

  lightbulb:         "\U000F0335"
  ceiling_light:     "\U000F0769"
  lamp:              "\U000F06B5"
  floor_lamp:        "\U000F08DD"
  string_lights:     "\U000F12BA"
  track_light:       "\U000F0914"
  bulkhead_light:    "\U000F1A2F"
  led_strip:         "\U000F07D6"
  coach_lamp:        "\U000F1020"
  ceiling_fan_light: "\U000F1798"
  night_icon:        "\U000F0594"

  home_icon:  "\U000F02DC"
  menu_left:  "\U000F035E"
  menu_right: "\U000F035F"

  navbar_font: light24

  weather_font: roboto48

  icon_font: light40
  text_font: roboto18
  screen_height: "480px"
  screen_width: "480px"
  sdl_height: "480"
  sdl_width: "480"  
  button_on_color: "burnt_sienna"
  button_off_color: "very_dark_gray"
  icon_on_color: "yellow"
  icon_off_color: "gray"
  label_on_color: "white"
  label_off_color: "gray"
  button_text_color: "white"
  button_height_single: '98px'
  button_height_double: '206px'
  button_width: '150px'
  touchscreen_idle_timeout: "30s"
  touchscreen_daytime_brightness: "100%"
  touchscreen_nighttime_brightness: "50%"

  # Screen goes to sleep at Mightnight
  screen_sleep_hour: '0'
  screen_sleep_minute: '0'

  # Screen wakes up at 5:30am
  screen_wake_hour: '5'
  screen_wake_minute: '30'

  button_1_name: "Bedroom"
  button_1_id: bedroom_light
  button_1_icon: $lightbulb
  button_1_device: "switch.sonoff_100176490c"

  button_2_name: "Dresser"
  button_2_id: dresser_light
  button_2_icon: $lightbulb
  button_2_device: "switch.sonoff_1001764e3e"

  button_3_name: "Living Room"
  button_3_id: living_room_light
  button_3_icon: $lightbulb
  button_3_device: "switch.sonoff_100176394b"

  button_4_name: "Night Mode"
  button_4_id: night_mode_switch
  button_4_icon: $night_icon
  button_4_device: "input_boolean.night_mode"

  button_5_name: "Night Mode"
  button_5_id: night_mode_switch
  button_5_icon: $night_icon
  button_5_device: "input_boolean.night_mode"

  button_6_name: "Night Mode"
  button_6_id: night_mode_switch
  button_6_icon: $night_icon
  button_6_device: "input_boolean.night_mode"

  button_7_name: "Night Mode"
  button_7_id: night_mode_switch
  button_7_icon: $night_icon
  button_7_device: "input_boolean.night_mode"

  button_8_name: "Night Mode"
  button_8_id: night_mode_switch
  button_8_icon: $night_icon
  button_8_device: "input_boolean.night_mode"

globals:
  - id: late_night_mode
    type: bool
    restore_value: false
    initial_value: 'false'

packages:
  base: !include modules/common_base.yaml
  colors: !include modules/common/color.yaml
  fonts: !include modules/common/fonts.yaml  
  time: !include modules/lvgl/lvgl_time_homeassistant.yaml
  clock: !include modules/lvgl/clock_scripts.yaml
  weather: !include modules/lvgl/weather_text_sensors.yaml

  ############
  # SDL
  ############
  hardware: !include modules/hardware/SDL-lvgl.yaml
  sensors: !include modules/lvgl/lvgl_sensors_base-SDL.yaml

  ###########
  # Sensecap
  ###########
  # webserver: !include modules/wifi_base.yaml
  # hardware: !include modules/hardware/sensecap-indicator.yaml
  # sensors: !include modules/lvgl/lvgl_sensors_base.yaml

esphome:
  on_boot:
    priority: -100
    then:
      - delay: 60s
      - lvgl.page.show: main_page

# -------------------------------------------------------------------------
# Button state - Update state for Homeassistant objects and internal relays
# -------------------------------------------------------------------------

# Homeassistant switches go here
text_sensor:
  - !include { file: modules/lvgl/basic_switch_button_state.yaml, vars: { id: 1 } }
  - !include { file: modules/lvgl/basic_switch_button_state.yaml, vars: { id: 2 } }
  - !include { file: modules/lvgl/basic_switch_button_state.yaml, vars: { id: 3 } }
  - !include { file: modules/lvgl/basic_boolean_button_state.yaml, vars: { id: 4 } }

#-------------------------------------------
# LVGL pages and Buttons
#-------------------------------------------

# Wake screen on touch
touchscreen:
  on_touch:
    then:
      - logger.log: "LVGL is active"
      - lvgl.resume:
      - if:
      # Only turn on baclight and set to 50% if late_night_mode is on
          condition:
            - lambda: |-
                return id(late_night_mode);
          then:
            - light.turn_on:
                id: display_backlight
                brightness: 50%
          else:
            - light.turn_on:
                id: display_backlight
                brightness: 100%

# Main LVGL section
lvgl:
  displays:
    - my_display
  touchscreens:
    - my_touchscreen
  on_idle: !include { file: modules/lvgl/lvgl_touchscreen_idle.yaml }

  theme: !include { file: modules/lvgl/lvgl_theme.yaml }
  page_wrap: true

# # Boot Screen
#   top_layer: !include { file: modules/lvgl/boot_screen.yaml }

  # Persistent navbar in top layer
  top_layer:
    widgets:
      - obj:
          align: bottom_mid
          scrollable: false
          bg_color: Black
          border_opa: TRANSP
          bg_opa: cover
          width: 100%
          height: 10%
          widgets:
            - !include modules/lvgl/navbar.yaml

# Main Page
  pages:
    - id: boot_page
      scrollable: false
      bg_color: Black
      border_opa: TRANSP
      bg_opa: cover
      widgets:
        - !include modules/lvgl/boot_page.yaml

    - id: main_page
      scrollable: false
      bg_color: Black
      border_opa: TRANSP
      bg_opa: cover
      pad_all: 5
      widgets:
      # button container
      - obj: # a properly placed container object for all these controls
          align: top_mid
          scrollable: false
          bg_color: Black
          border_opa: TRANSP
          bg_opa: cover
          width: 100%
          height: 90%
          layout: # enable the FLEX layout for the children widgets
            type: FLEX
            flex_flow: COLUMN_WRAP # the order of the widgets starts top left
            flex_align_cross: CENTER # they sould be centered
          widgets:
            - button: !include { file: modules/lvgl/basic_switch_button.yaml, vars: { id: 1, height: $button_height_double } }
            - button: !include { file: modules/lvgl/basic_switch_button.yaml, vars: { id: 2, height: $button_height_double } }
            - button: !include { file: modules/lvgl/basic_switch_button.yaml, vars: { id: 3, height: $button_height_double } }
            - button: !include { file: modules/lvgl/basic_boolean_button.yaml, vars: { id: 4, height: $button_height_double } }
            
            - button: !include { file: modules/lvgl/basic_boolean_button.yaml, vars: { id: 5, height: $button_height_single } }
            - button: !include { file: modules/lvgl/basic_boolean_button.yaml, vars: { id: 6, height: $button_height_single } }
            - button: !include { file: modules/lvgl/basic_boolean_button.yaml, vars: { id: 7, height: $button_height_single } }
            - button: !include { file: modules/lvgl/basic_boolean_button.yaml, vars: { id: 8, height: $button_height_single } }
    
    # Clock
    - id: clock_page
      scrollable: false
      bg_color: Black
      border_opa: TRANSP
      bg_opa: cover
      pad_all: 5
      widgets:
        - obj: # Clock container
            align: top_mid
            height: 90%
            width: 100%
            bg_color: Black
            border_opa: TRANSP
            bg_opa: cover
            widgets:
              - !include modules/lvgl/clock_widget.yaml

    # Weather
    - id: weather_page
      scrollable: false
      bg_color: Black
      border_opa: TRANSP
      bg_opa: cover
      pad_all: 5
      widgets:
        - obj: # Weather container
            align: top_mid
            height: 90%
            width: 100%
            bg_color: Black
            border_opa: TRANSP
            bg_opa: cover
            widgets:
              - !include modules/lvgl/weather_widget.yaml

#-------------------------------------------
# Graphics and Fonts
#-------------------------------------------
image:
  - file: https://esphome.io/_static/logo-text-on-light.svg
    id: boot_logo
    resize: 460x90
    type: RGB565
    transparency: alpha_channel


